version: '3'
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    networks:
      - calcnet

  web:
    build: ./web
    ports:
      - "8080:80"
    networks:
      - calcnet

networks:
  calcnet:
