version: '3.8'

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: user-service
    networks:
      - app-network

  order-service:
    build: ./order-service
    container_name: order-service
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    expose:
      - 80
    networks:
      - app-network

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf         # ← ADD THIS LINE
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - auth-service
      - user-service
      - order-service
      - frontend
    networks:
      - app-network


networks:
  app-network:
