version: '3.8'

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: user-service
    networks:
      - app-network

  order-service:
    build: ./order-service
    container_name: order-service
    networks:
      - app-network

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html:ro  # Serve static HTML from here
    depends_on:
      - auth-service
      - user-service
      - order-service
    networks:
      - app-network

networks:
  app-network:
